version: '3'
services:
    db:
        image: mysql:8.0.30
        container_name: mysqlTEST
        restart: always
        ports:
            - '127.0.0.1:3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./initMysql.sh:/docker-entrypoint-initdb.d/initMysql.sh
            - ./localTest.sql:/var/data/localTest.sql